from pyurfa import Urfa

obj = Urfa({'xml':'xml/api_53-005.xml','debug':False})
userinfo=obj.rpcf_get_userinfo({'user_id':22 })
print(userinfo)
userinfo = obj.rpcf_get_user_contacts({'user_id': 22})
print(userinfo)
users=obj.rpcf_get_users_list({'from':0,'to':255 })
print(users)
users=obj.rpcf_get_accountinfo({'account_id':22})
print(users)
users=obj.rpcf_get_user_account_list({'user_id':22})
print(users)
users=obj.rpcf_get_sys_settings({})
print(users)
users=obj.rpcf_get_all_services_for_user({'account_id':22})
print(users)
users=obj.rpcf_get_periodic_service_link({'slink_id':2})
print(users)
users=obj.rpcf_get_once_service_link({'slink_id':2})
print(users)
users=obj.rpcf_get_houses_list({})
print(users)
users=obj.rpcf_get_periodic_link_stats({'slink_id':2})
print(users)